apiVersion: v1
kind: Service
metadata:
  name: {{ include "foreman.fullname" . }}-frontend
  labels:
    {{- include "foreman.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "foreman.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
